name: "t3-chat"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "t3chatbuild"
    ports:
      - "5432:5432"
    restart: always
